name: TRMNL Vision Auto-Fix

on:
  push:
  workflow_dispatch:

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing commits back
    env:
      # --- App & patcher behavior ---
      USE_LOCAL_MODE: "1"     # use local transformers (no HF Inference API)
      ACCEPTANCE_HINT: "NFL games should render in the correct sections/columns with accurate team/date labels; no misplacements."
      APP_URL: "http://localhost:4567"
      TRMNL_CONTAINER_NAME: "trmnlp"
      AI_PATCH_MAX_ATTEMPTS: "3"
      WAIT_BOOT_SECS: "10"

      # --- Models (lighter captioner for CI reliability) ---
      CAPTION_MODEL_ID: "nlpconnect/vit-gpt2-image-captioning"
      TEXT_MODEL_ID: "google/flan-t5-base"
      TEXT_MODEL_ARCH: "seq2seq"  # or "causal"

      # --- HF/Transformers settings ---
      TRANSFORMERS_VERBOSITY: "info"
      HF_HUB_DISABLE_TELEMETRY: "1"
      HF_HUB_ENABLE_HF_TRANSFER: "0"  # avoid requiring hf_transfer on runners

      # --- Caches (keep them inside workspace) ---
      HF_HOME: ${{ github.workspace }}/.gh-cache/huggingface
      TRANSFORMERS_CACHE: ${{ github.workspace }}/.gh-cache/huggingface/transformers
      TORCH_HOME: ${{ github.workspace }}/.gh-cache/torch

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare cache directories
        run: |
          mkdir -p "$HF_HOME" "$TRANSFORMERS_CACHE" "$TORCH_HOME" artifacts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (CPU only)
        run: |
          python -m pip install --upgrade pip
          # Torch >=2.6 satisfies the CVE requirement; 2.8.0 cpu is stable on runners
          pip install "torch==2.8.0" --index-url https://download.pytorch.org/whl/cpu
          pip install "transformers>=4.41" "accelerate>=0.33" pillow requests

      - name: Install Node + Playwright (Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          test -f package.json || npm init -y
          npm install playwright
          npx --yes playwright install --with-deps chromium

      - name: Configure git identity (for pushes)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Run vision patcher
        shell: bash
        run: |
          set -euxo pipefail
          python -u tools/ai_vision_patcher.py || {
            echo "---- PATCHER FAILED; dumping artifacts ----"
            ls -la artifacts || true
            for f in artifacts/error.txt artifacts/raw_model_output.txt artifacts/last_diff.patch; do
              if [[ -f "$f" ]]; then
                echo "----- $f -----"
                sed -n '1,200p' "$f" || true
              fi
            done
            exit 1
          }

      - name: Commit and push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "🤖 Auto-fix from CI"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: trmnl-autofix-artifacts
            path: |
              artifacts/**
              .gh-cache/huggingface/transformers/*
              .gh-cache/torch/*
            if-no-files-found: ignore
