name: TRMNL Vision Auto-Fix

on:
  push:
  workflow_dispatch:

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Keep model/cache out of repo
      HF_HOME: ${{ runner.temp }}/.cache/huggingface
      TRANSFORMERS_CACHE: ${{ runner.temp }}/.cache/huggingface/transformers
      TORCH_HOME: ${{ runner.temp }}/.cache/torch

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (CPU)
        run: |
          python -m pip install --upgrade pip
          # Torch CPU build (faster & smaller than CUDA)
          pip install "torch==2.3.1+cpu" --index-url https://download.pytorch.org/whl/cpu
          pip install "transformers>=4.41" "accelerate>=0.33" pillow requests

      - name: Install Node + Playwright (Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          test -f package.json || npm init -y
          npm install playwright
          npx --yes playwright install --with-deps chromium

      - name: Run vision patcher (LOCAL mode, BLIP + FLAN-T5)
        env:
          USE_LOCAL_MODE: "1"        # run locally with transformers
          ACCEPTANCE_HINT: "NFL games should render in the correct sections/columns with accurate team/date labels; no misplacements."
          APP_URL: http://localhost:4567
          TRMNL_CONTAINER_NAME: trmnlp
          AI_PATCH_MAX_ATTEMPTS: "3"
          WAIT_BOOT_SECS: "10"
          # Models (override here without code changes)
          CAPTION_MODEL_ID: "Salesforce/blip-image-captioning-base"
          TEXT_MODEL_ID: "google/flan-t5-large"
          TEXT_MODEL_ARCH: "seq2seq"   # "seq2seq" or "causal"
        run: python tools/ai_vision_patcher.py

      - name: Push changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git push
          else
            echo "No changes."
          fi
